// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzTIGhkuS_pkcTKgtdH3ZK2SGs2YI0s8U',
    appId: '1:284741735704:web:c7571127b279034ea23a6d',
    messagingSenderId: '284741735704',
    projectId: 'chat-app-flutter-59780',
    authDomain: 'chat-app-flutter-59780.firebaseapp.com',
    storageBucket: 'chat-app-flutter-59780.appspot.com',
    measurementId: 'G-42E6RX38HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXw2duCC_bFFAdfnHXaxZqZLsGbLDs1Y',
    appId: '1:284741735704:android:40c521c63d44f972a23a6d',
    messagingSenderId: '284741735704',
    projectId: 'chat-app-flutter-59780',
    storageBucket: 'chat-app-flutter-59780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbm6b93RntCwzAti4DO8pK_SG9ulXl1j0',
    appId: '1:284741735704:ios:212eaaa9df5bca8ea23a6d',
    messagingSenderId: '284741735704',
    projectId: 'chat-app-flutter-59780',
    storageBucket: 'chat-app-flutter-59780.appspot.com',
    iosClientId: '284741735704-ud03p7220me442ukujcd5b3qn770bnve.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbm6b93RntCwzAti4DO8pK_SG9ulXl1j0',
    appId: '1:284741735704:ios:212eaaa9df5bca8ea23a6d',
    messagingSenderId: '284741735704',
    projectId: 'chat-app-flutter-59780',
    storageBucket: 'chat-app-flutter-59780.appspot.com',
    iosClientId: '284741735704-ud03p7220me442ukujcd5b3qn770bnve.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
